version = 1

test_patterns = [
  "**/*_test.go"
]


[[analyzers]]
name = "go"
enabled = true
runtime_version = "3.x.x"

[analyzers.meta]
import_path = "github.com/mellowdrifter/rpkirtr"

[[analyzers]]
name = "test-coverage"
enabled = true